### ISSUE TITLE
Missing keywords and properties - image library

### ISSUE THREAD

**Issue by jimenezpf** [slag-plt/scamper-lang#1]
I was testing code that I was able to run in Racket. The following keywords or properties are not recognized or I don't know how to write them properly in scamper.

- The keywords to define a pen, ellipse, or triangle are not recognized, either a way to specify alignment or offset.  
- A way to specify transparency or opacity of the shape. Usually, we write a number before the color

**Comment by psosera** [comment]
Yup! Need to provide implementations for those primitives. Ellipse and triangle should be easy. I think the various alignment/offset primitives are useful, but `pen` might be more trouble than it is worth.

For transparency and opacity, the color string is directly passed to the `canvas` object which accepts a string of the form `rgba(r, b, g, a)` for a 3-valued color along with its alpha value. I updated the documentation to reflect that, but I'll also work on fixing the API to look like the Racket API.

**Comment by psosera** [comment]
I added a function `(color r g b a)` to create color strings from numbers as well as a `square` primitive. I'm refactoring the web renderer (slag-plt/web-support) so that I can add new image primitives without having to go through VSCode.
