### ISSUE TITLE
odd? and even? accept non-integers

### ISSUE THREAD

**Issue by SASUKE38** [slag-plt/scamper-lang#71]
Passing non-integers to odd? and even? is allowed. When given a non-integer, the functions seem to ignore that the input has a decimal.
```racket
(odd? 3.78)
(odd? 4.1)
(even? 4.5)
(even? 5.9)
```
The calls above return the following values:
```racket
#t

#f

#t

#f
```

**Comment by psosera** [comment]
Thanks for reporting this, @SASUKE38!
